### ISSUE TITLE
Why do I get no attribute "backend" when backend is in the folder?

### ISSUE THREAD

**Issue by lijuncheng16** [datalogai/recurrentshop#19]
xxx@ubuntu:~/$ sudo python speed_test.py 
Using Theano backend.
Traceback (most recent call last):
  File "speed_test.py", line 1, in <module>
    from recurrentshop import*
  File "build/bdist.linux-x86_64/egg/recurrentshop/__init__.py", line 1, in <module>
  File "build/bdist.linux-x86_64/egg/recurrentshop/engine.py", line 32, in <module>
AttributeError: 'module' object has no attribute 'backend'

Somehow it gave me this error, any idea what's going on?

**Comment by lijuncheng16** [comment]
NVM. Fixed it. Seems my keras was 1.0.3 that didn't support K.backend() method.
