### ISSUE TITLE
Errors when running the speed_test.py

### ISSUE THREAD

**Issue by realcrane** [datalogai/recurrentshop#23]
Hi,

Thanks for this great package. I just came across it and wanted to try. However, when I run the speed_test.py in the examples, the code segment for testing the recurrentshop model reported the following errors:

----------------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\software\Python\Miniconda3\lib\site-packages\theano\theano\tensor\var.py", line 592, in __iter__
    for i in xrange(theano.tensor.basic.get_vector_length(self)):
  File "D:\software\Python\Miniconda3\lib\site-packages\theano\theano\tensor\basic.py", line 4463, in get_vector_length
    v)
TypeError: argument must be symbolic vector, got '<TensorType(float32, matrix)>'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".\DeepMotion.py", line 164, in <module>
    model.train_on_batch(x[:1], y[:1])  # force compile
  File "D:\software\Python\Miniconda3\lib\site-packages\keras\keras\models.py", line 758, in train_on_batch
    class_weight=class_weight)
  File "D:\software\Python\Miniconda3\lib\site-packages\keras\keras\engine\training.py", line 1266, in train_on_batch
    self._make_train_function()
  File "D:\software\Python\Miniconda3\lib\site-packages\keras\keras\engine\training.py", line 720, in _make_train_function
    **self._function_kwargs)
  File "D:\software\Python\Miniconda3\lib\site-packages\keras\keras\backend\theano_backend.py", line 902, in function
    return Function(inputs, outputs, updates=updates, **kwargs)
  File "D:\software\Python\Miniconda3\lib\site-packages\keras\keras\backend\theano_backend.py", line 881, in __init__
    for v, nv in updates:
  File "D:\software\Python\Miniconda3\lib\site-packages\theano\theano\tensor\var.py", line 596, in __iter__
    raise TypeError(('TensorType does not support iteration. '
TypeError: TensorType does not support iteration. Maybe you are using builtin.sum instead of theano.tensor.sum? (Maybe .max?)
------------------------------------------------------------------------------------------------------

I am using Python 3.5, Theano 0.9 dev, Keras 1.1.2. I wonder if somebody can help me to identify the problem.

**Comment by jfowkes** [comment]
recurrentshop hasn't been upgraded for the newest Keras yet, try downgrading to Keras 1.1.2

**Comment by realcrane** [comment]
@jfowkes Hi, thanks for the reply! I am using Keras 1.1.2.

**Comment by jfowkes** [comment]
@realcrane Oh so you are, sorry! I would try with Theano 0.8.2 rather than the dev version. That combination works for me on python 2.7.

**Comment by realcrane** [comment]
@jackccrawford  thanks again! I tried python 2.7 + theano 0.8 + Keras 1.1.2. But a similar error occurred:

>>> test_container.test_all()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\Software\Python\Miniconda3\envs\py27\lib\site-packages\keras\utils\test_utils.py", line 128, in wrapper
    output = func(*args, **kwargs)
  File "test_container.py", line 35, in test_all
    model.fit(x, y, nb_epoch=1)
  File "D:\Software\Python\Miniconda3\envs\py27\lib\site-packages\keras\models.py", line 664, in fit
    sample_weight=sample_weight)
  File "D:\Software\Python\Miniconda3\envs\py27\lib\site-packages\keras\engine\training.py", line 1115, in fit
    self._make_train_function()
  File "D:\Software\Python\Miniconda3\envs\py27\lib\site-packages\keras\engine\training.py", line 720, in _make_train_function
    **self._function_kwargs)
  File "D:\Software\Python\Miniconda3\envs\py27\lib\site-packages\keras\backend\theano_backend.py", line 929, in function
    return Function(inputs, outputs, updates=updates, **kwargs)
  File "D:\Software\Python\Miniconda3\envs\py27\lib\site-packages\keras\backend\theano_backend.py", line 908, in __init__
    for v, nv in updates:
  File "D:\Software\Python\Miniconda3\envs\py27\lib\site-packages\theano\tensor\var.py", line 553, in __iter__
    raise TypeError(('TensorType does not support iteration. '
TypeError: TensorType does not support iteration. Maybe you are using builtin.sum instead of theano.tensor.sum? (Maybe .max?)

**Comment by realcrane** [comment]
@jfowkes I deleted my previous post because I have figured it out. Sorry that I had multiple envs with the same module but of different versions. Sometimes they cross reference. Again, I am very grateful.

**Comment by jfowkes** [comment]
@realcrane No worries, glad to have helped!

**Comment by 7oranger** [comment]
Are you using CPU or GPU ? I encountered this problem(TypeError: TensorType does not support iteration. Maybe you are using builtin.sum instead of theano.tensor.sum? (Maybe .max?)) on CPU. But it didnot appear on GPU. (I'm using theano backend, python 2,7 windows 64 bit, newest keras)

**Comment by realcrane** [comment]
@7oranger I didn't try the CPU version. Anyway, aside from python 2.7, theano 0.8.2 and keras 1.1.2 would be a safe bet.
