### ISSUE TITLE
TensorType does not support iteration error with newest Keras and Theano Backend

### ISSUE THREAD

**Issue by Phylliida** [datalogai/recurrentshop#25]
When I'm up to date with the Keras Branch and using the backend, I get the following error with the examples on the github readme when calling fit.

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Other\Python27\python-2.7.10.amd64\lib\site-packages\keras\models.py", line 664, in fit
    sample_weight=sample_weight)
  File "C:\Other\Python27\python-2.7.10.amd64\lib\site-packages\keras\engine\training.py", line 1115                                                                                                 , in fit
    self._make_train_function()
  File "C:\Other\Python27\python-2.7.10.amd64\lib\site-packages\keras\engine\training.py", line 720,                                                                                                  in _make_train_function
    **self._function_kwargs)
  File "C:\Other\Python27\python-2.7.10.amd64\lib\site-packages\keras\backend\theano_backend.py", li                                                                                                 ne 929, in function
    return Function(inputs, outputs, updates=updates, **kwargs)
  File "C:\Other\Python27\python-2.7.10.amd64\lib\site-packages\keras\backend\theano_backend.py", li                                                                                                 ne 908, in __init__
    for v, nv in updates:
  File "C:\Other\Python27\python-2.7.10.amd64\lib\site-packages\theano\tensor\var.py", line 584, in                                                                                                  __iter__
    raise TypeError(('TensorType does not support iteration. '
TypeError: TensorType does not support iteration. Maybe you are using builtin.sum instead of theano.                                                                                                 tensor.sum? (Maybe .max?)
```

However, if I revert to [this](https://github.com/fchollet/keras/blob/d745d9ee96e5d39393ac740e5b84229beca00f1d/keras/backend/theano_backend.py) then it starts working. What broke?

**Comment by sun-peach** [comment]
Hi, I have the same issue now. Could you tell me how you fix this problem? Thank you. @Phylliida

**Comment by 7oranger** [comment]
Hi. I am using the theano backend on windows 6.4 for python2.7 and I encountered the same question.
Did you solve the problem? @Phylliida @sun-peach 

>  raise TypeError(('TensorType does not support iteration. '
> TypeError: TensorType does not support iteration. Maybe you are using builtin.sum instead of theano.tensor.sum? (Maybe .max?)

**Comment by Phylliida** [comment]
Yes, if you revert to [this revision](https://github.com/fchollet/keras/blob/d745d9ee96e5d39393ac740e5b84229beca00f1d/keras/backend/theano_backend.py) then it works (just copy paste that file into your theano_backend.py in your keras folder)  . I'd like to use the more recent version but that is a temporary fix.

**Comment by fighting41love** [comment]
@Phylliida Thanks. Problem solved.

**Comment by Bamboo-TNLP** [comment]
@fighting41love 
How to solve it? Thanks.
