### ISSUE TITLE
TypeError: step() missing 1 required positional argument: 'weights.

### ISSUE THREAD

**Issue by wujun** [datalogai/recurrentshop#3]
The backend of Keras is Tensorflow and my python envorinment is v3.4.3. After installed the package by pip I tried to run test.py in the test folder without any modification. My program is blocked when It runs to initial_states = self.get_initial_states(x) in engine.py and pop up a type error:
"TypeError: step() missing 1 required positional argument: 'weights."

The trackback looks like below:
Traceback (most recent call last):
  File "/Applications/PyCharm CE.app/Contents/helpers/pydev/pydevd.py", line 1556, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/Applications/PyCharm CE.app/Contents/helpers/pydev/pydevd.py", line 940, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/Applications/PyCharm CE.app/Contents/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/apple/Documents/workspace/dl/recurrentshop/tests/test.py", line 11, in <module>
    model.add(rc)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/keras/models.py", line 275, in add
    layer.create_input_layer(batch_input_shape, input_dtype)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/keras/engine/topology.py", line 367, in create_input_layer
    self(x)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/keras/engine/topology.py", line 511, in __call__
    self.add_inbound_node(inbound_layers, node_indices, tensor_indices)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/keras/engine/topology.py", line 569, in add_inbound_node
    Node.create_node(self, inbound_layers, node_indices, tensor_indices)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/keras/engine/topology.py", line 150, in create_node
    output_tensors = to_list(outbound_layer.call(input_tensors[0], mask=input_masks[0]))
  File "/Users/apple/Documents/workspace/dl/recurrentshop/recurrentshop/engine.py", line 285, in call
    initial_states = self.get_initial_states(x)
  File "/Users/apple/Documents/workspace/dl/recurrentshop/recurrentshop/engine.py", line 370, in get_initial_states
    input = layer.step(input, layer_initial_states)[0]
TypeError: step() missing 1 required positional argument: 'weights'
Could you give any suggestion to resolve the issue?

**Comment by farizrahman4u** [comment]
Are you sure your recurrentshop version is up to date?
Did you change anything yourself? Its suppose to be input = layer._step(...) not layer.step(...)

**Comment by wujun** [comment]
Sorry, it's my bad. I modified some code in your libraray according to PEP8's suggestions including changed layer.step(...) to layer_step(...) . Although another issue still happened I think this issue has gone and closed the thread
