### ISSUE TITLE
Training fails

### ISSUE THREAD

**Issue by abhaikollara** [datalogai/recurrentshop#39]
I'm trying to train a recurrent model using SGD and it throws this error. Can't seem to figure out what's going on since the error does not come from Recurrent Shop itself.

Here's the [code](https://gist.github.com/abhaikollara/021cd5a82b7d8020b9eedde7866cbfda)

```
Using TensorFlow backend.
Traceback (most recent call last):
  File "main.py", line 18, in <module>
    RWAModel.fit(train_data, train_labels)
  File "/home/abhai/keras/keras/engine/training.py", line 1458, in fit
    self._make_train_function()
  File "/home/abhai/keras/keras/engine/training.py", line 1002, in _make_train_function
    self.total_loss)
  File "/home/abhai/keras/keras/optimizers.py", line 398, in get_updates
    m_t = (self.beta_1 * m) + (1. - self.beta_1) * g
  File "/home/abhai/.local/lib/python2.7/site-packages/tensorflow/python/ops/math_ops.py", line 793, in binary_op_wrapper
    y = ops.convert_to_tensor(y, dtype=x.dtype.base_dtype, name="y")
  File "/home/abhai/.local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 637, in convert_to_tensor
    as_ref=False)
  File "/home/abhai/.local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 702, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/home/abhai/.local/lib/python2.7/site-packages/tensorflow/python/framework/constant_op.py", line 110, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/home/abhai/.local/lib/python2.7/site-packages/tensorflow/python/framework/constant_op.py", line 99, in constant
    tensor_util.make_tensor_proto(value, dtype=dtype, shape=shape, verify_shape=verify_shape))
  File "/home/abhai/.local/lib/python2.7/site-packages/tensorflow/python/framework/tensor_util.py", line 360, in make_tensor_proto
    raise ValueError("None values not supported.")
ValueError: None values not supported.
```

**Comment by farizrahman4u** [comment]
Paste code for RAWmodel

**Comment by farizrahman4u** [comment]
Never mind..

**Comment by farizrahman4u** [comment]
Is it working on theano backend?

**Comment by abhaikollara** [comment]
Nope, getting a `theano.gradient.DisconnectedInputError`
```
Traceback (most recent call last):
  File "main.py", line 18, in <module>
    RWAModel.fit(train_data, train_labels)
  File "/home/abhai/keras/keras/engine/training.py", line 1458, in fit
    self._make_train_function()
  File "/home/abhai/keras/keras/engine/training.py", line 1002, in _make_train_function
    self.total_loss)
  File "/home/abhai/keras/keras/optimizers.py", line 381, in get_updates
    grads = self.get_gradients(loss, params)
  File "/home/abhai/keras/keras/optimizers.py", line 47, in get_gradients
    grads = K.gradients(loss, params)
  File "/home/abhai/keras/keras/backend/theano_backend.py", line 1136, in gradients
    return T.grad(loss, variables)
  File "/usr/local/lib/python2.7/dist-packages/theano/gradient.py", line 538, in grad
    handle_disconnected(elem)
  File "/usr/local/lib/python2.7/dist-packages/theano/gradient.py", line 525, in handle_disconnected
    raise DisconnectedInputError(message)
theano.gradient.DisconnectedInputError:  
Backtrace when that variable is created:

  File "main.py", line 10, in <module>
    rwa = RWA(input_dim, output_dim)
  File "/home/abhai/DL/RWA/RWACell.py", line 24, in RWA
    u = Dense(output_dim)(x)
  File "/home/abhai/keras/keras/engine/topology.py", line 551, in __call__
    self.build(input_shapes[0])
  File "/home/abhai/keras/keras/layers/core.py", line 833, in build
    constraint=self.bias_constraint)
  File "/home/abhai/keras/keras/engine/topology.py", line 384, in add_weight
    weight = K.variable(initializer(shape), dtype=K.floatx(), name=name)
  File "/home/abhai/keras/keras/backend/theano_backend.py", line 146, in variable
    strict=False)
```

**Comment by farizrahman4u** [comment]
Did you use tf.divide on a theano tensor?

**Comment by abhaikollara** [comment]
Yup :grimacing: Lemme fix that and try again

**Comment by farizrahman4u** [comment]
Ok, the issue seems to be that certain weights have no effect on the final output `ht`.. You can fixing it by : `ht = ht + 0. * nt`.. this way ht becomes differential w.r.to nt.. (nt is already differential w.r.to the weights)

Following script works for me on theano backend:

```python

from keras.layers import *
from keras.models import *
from recurrentshop import *

def RWA(input_dim, output_dim):
    x = Input((input_dim, ))
    h_tm1 = Input((output_dim, ))
    n_tm1 = Input((output_dim, ))
    d_tm1 = Input((output_dim, ))

    x_h = concatenate([x, h_tm1])  # Concatenated vector

    u = Dense(output_dim)(x)
    g = Dense(output_dim, activation='tanh')(x_h)

    a = Dense(output_dim, use_bias=False)(x_h)
    e_a = Lambda(lambda x: K.exp(x))(a)

    z = multiply([u, g])
    nt = add([n_tm1, multiply([z, e_a])])
    dt = add([d_tm1, e_a])
    ht = Lambda(lambda x: 1. / x)(dt)
    ht = Activation('tanh')(ht)
    # Fix gradient issue
    zeros = Lambda(lambda x: x * 0.)(nt)
    ht = add([ht, zeros])

    return RecurrentModel(input=x, output=ht,
                          initial_states=[h_tm1, n_tm1, d_tm1],
                          final_states=[ht, nt, dt])


rnn = RWA(5, 10)

input = Input((7, 5))
output = rnn(input)


model = Model(input, output)

model.compile(loss='mse', optimizer='sgd')

model.fit(np.random.random((32, 7, 5)), np.random.random((32, 10)))

model.predict(np.random.random((32, 7, 5)))
```

**Comment by abhaikollara** [comment]
Works for me on Tensorflow
